AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DeploymentId:
    Type: String
  ClaimCheckQueueArn:
    Type: String
  LandingBucketName:
    Type: String

Resources:
  ConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "consumer-function-${DeploymentId}"
      CodeUri: ../
      Handler: consumer.handler
      Runtime: python3.11
      MemorySize: 512
      Architectures:
        - x86_64
      Timeout: 600
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref ClaimCheckQueueArn
            BatchSize: 1
            Enabled: true
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - SQSPollerPolicy:
            QueueName: !Select [5, !Split [":", !Ref ClaimCheckQueueArn]]
        - S3ReadPolicy:
            BucketName: !Ref LandingBucketName

Outputs:
  ConsumerFunctionName:
    Value: !Ref ConsumerFunction
